LESSONS = [
    "الفبا",
    "تلفظ",
    "اعداد",
    "روزها",
    "ماه‌ها",
    "واژگان پایه",
    "معرفی خود",
    "جملات ساده",
    "سطح A1",
    "سطح A2",
    "سطح B1",
    "سطح B2",
    "سطح C1",
    "گرامر",
    "مکالمه",
    "Reading",
    "Listening",
    "Writing",
    "Academic English",
    "Business English",
    "Banking English",
    "Marketing English",
]
